apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: web-app
spec:
  selector:
    app: portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
