apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: web-app
spec:
  type: LoadBalancer
  selector:
    app: portfolio
  ports:
    - name: portfolio-port
      protocol: TCP
      port: 80
      targetPort: 8080
